### PR TITLE
fix #38: fix backtracking issues in Lua

### LINKED ISSUE #38: Regular expression causes exponential backtracking on Lua
1. This part of the regular expression may cause exponential backtracking on strings starting with `'{!,'` and containing many repetitions of `'!,'`.
https://github.com/teknologi-umum/flourite/blob/313def7cd86104ee0fdfbc7b5a1c21bcaddb87f7/src/languages/lua.ts#L30

2. This part of the regular expression may cause exponential backtracking on strings starting with` '{!=!,'` and containing many repetitions of `'!=!,'`.
https://github.com/teknologi-umum/flourite/blob/313def7cd86104ee0fdfbc7b5a1c21bcaddb87f7/src/languages/lua.ts#L32

According to the [LGTM rule](https://lgtm.com/rules/1505904457770/) (click that link to see detailed rule):

Some regular expressions take a long time to match certain input strings to the point where the time it takes to match a string of length n is proportional to n<sup>k</sup> or even 2<sup>n</sup>. Such regular expressions can negatively affect performance, or even allow a malicious user to perform a Denial of Service ("DoS") attack by crafting an expensive input string for the regular expression to match.

See [LGTM](https://lgtm.com/projects/g/teknologi-umum/flourite/rev/454db47e3b83ae4b9d59ed1a80d86dadea044511) for the detailed issue.

### PR DESCRIPTION
**Pull request by farhan443**
fix #38

Seems like overlapping patterns is the cause of this exponential backtracking.
Those patterns are `\S` and `(,|;)` because punctuations are also non-whitespace characters, hence they can be matched by `\S` as well.

I've replaced `\S` with `[^\s;,]` to prevent them from overlapping.

### CODE REVIEW

**Review by elianiva — COMMENTED** [review]
CI unrelated, mau merge takut anu

**Comment by aldy505** [comment]
While this is still in the `lua.ts` file and considering the alert from CodeQL, can you also fix this one? @farhan443 

image

you can see the annotation here: https://github.com/teknologi-umum/flourite/pull/60/files#annotation_2187805711

**Comment by farhan443** [comment]
> While this is still in the `lua.ts` file and considering the alert from CodeQL, can you also fix this one? @farhan443 
> 
> image
> 
> you can see the annotation here: https://github.com/teknologi-umum/flourite/pull/60/files#annotation_2187805711

Fixed

**Comment by farhan443** [comment]
> While this is still in the `lua.ts` file and considering the alert from CodeQL, can you also fix this one? @farhan443 
> 
> image
> 
> you can see the annotation here: https://github.com/teknologi-umum/flourite/pull/60/files#annotation_2187805711

Fixed @aldy505

**Review by aldy505 — APPROVED** [review]

**Pull request merged**
